import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./../compnents/Header"
import Footer from "./../compnents/Footer"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "finc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body suppressHydrationWarning={true}>
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}