import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./../compnents/Header"
import Footer from "./../compnents/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Include weights you need
});

export const metadata = {
  title: "finc",
   icons: {
    icon: '/favicon.ico',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${outfit.variable}`}>
      <body suppressHydrationWarning={true}>
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}